config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'friends#index'
  resources :friends do
    collection do
      get :party
      get :work
      get :school
      get :holidays
      get :other
    end
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
# == Schema Information
#
# Table name: friends
#
#  id           :bigint           not null, primary key
#  email        :string
#  friend_place :integer          default("other"), not null
#  name         :string
#  nickname     :string
#  surname      :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Friend < ApplicationRecord
  validates :name, :surname, presence: true, length: {minimum: 3}
  validates :email, uniqueness: true, length: {minimum: 3}, format: {with: URI::MailTo::EMAIL_REGEXP}

  enum friend_place: %i[party work holidays school other]

  scope :party, -> {where(friend_place: 'party')}
  scope :work, -> {where(friend_place: 'work')}
  scope :holidays, -> {where(friend_place: 'holidays')}
  scope :school, -> {where(friend_place: 'school')}
  scope :other, -> {where(friend_place: 'other')}

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base


end

app/controllers/friends_controller.rb
# frozen_string_literal: true

class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  layout 'application'
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show; end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def party
    @friends = Friend.party
  end

  def work
    @friends = Friend.work
  end

  def holidays
    @friends = Friend.holidays
  end

  def school
    @friends = Friend.school
  end

  def other
    @friends = Friend.other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:name, :nickname, :surname, :email, :friend_place)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def app_title
    "My Friends"
  end

end

app/helpers/friends_helper.rb
module FriendsHelper
  def nav_link_class(path)
    ['nav-link', ('active' if current_page?(path))]
  end
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-2">
    <%= form.label :name, style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
    <%= form.text_field :name, class: 'form-control', style: 'border-radius:0px;' %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :nickname, style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
    <%= form.text_field :nickname, class: 'form-control', style: 'border-radius:0px;' %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :surname, style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
    <%= form.text_field :surname, class: 'form-control', style: 'border-radius:0px;' %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :email, style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
    <%= form.text_field :email, class: 'form-control', style: 'border-radius:0px;' %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label 'Where did we meet?', style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
      <%= form.select :friend_place, Friend.friend_places.keys, { include_blank: 'Where did we meet...' }, class: 'form-select', style: 'border-radius:0px;' %>
    </div>
  </div>

  <div>
    <%= form.submit class: 'btn btn-success', style: 'border-radius:0px;' %>
  </div>

<% end %>

app/views/friends/_friend.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row mb-2">
    <%= form.label :name, style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
      <%= form.text_field :name, class: 'form-control', style: 'border-radius:0px;', disabled: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :nickname, style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
      <%= form.text_field :nickname, class: 'form-control', style: 'border-radius:0px;', disabled: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :surname, style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
      <%= form.text_field :surname, class: 'form-control', style: 'border-radius:0px;', disabled: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label :email, style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
      <%= form.text_field :email, class: 'form-control', style: 'border-radius:0px;', disabled: true %>
    </div>
  </div>

  <div class="row mb-2">
    <%= form.label 'Where did we meet?', style: "display: block", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-4">
      <%= form.select :friend_place, Friend.friend_places.keys, { include_blank: 'Where did we meet...' }, class: 'form-select', style: 'border-radius:0px;', disabled: true %>
    </div>
  </div>

<% end %>

app/views/friends/_friends_list.html.erb
<div id="friends" class="container">
  <table class="table align-middle">
    <thead>
    <tr>
      <th>Name</th>
      <th>Nickname</th>
      <th>Surname</th>
      <th>Email</th>
      <th>Where did we meet?</th>
      <th class="text-center">Actions</th>
    </tr>
    </thead>
    <tbody class="table-group-divider">
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.name %></td>
        <td><%= friend.nickname %></td>
        <td><%= friend.surname %></td>
        <td><%= friend.email %></td>
        <td><%= friend.friend_place %></td>
        <td class="text-center">
          <%= link_to "Show", friend, class: 'btn btn-info', style: 'border-radius:0px;' %>
          <%= link_to "Edit", edit_friend_path(friend), class: 'btn btn-success', style: 'border-radius:0px;' %>
          <%= link_to "Delete", @friend, class: 'btn btn-danger', style: 'border-radius:0px;', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this item?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/friends/edit.html.erb
<h1>Edit friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend, class: 'btn btn-info', style: 'border-radius:0px;'  %>
  <%= link_to "Back", friends_path, class: 'btn btn-dark', style: 'border-radius:0px;' %>
</div>

app/views/friends/holidays.html.erb
<h1>Friends met <b>on holidays</b></h1>

<br>
<%= render 'friends/friends_list' %>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "New friend", new_friend_path, class: 'btn btn-success', style: 'border-radius:0px;' %>
<br>

<%= render 'friends/friends_list' %>

app/views/friends/new.html.erb
<h1 class="text-center">New friend</h1>
<br>
<%= render "form", friend: @friend %>

<div>
  <%= link_to "Back", friends_path, class: 'btn btn-secondary', style: 'border-radius:0px;' %>
</div>

app/views/friends/other.html.erb
<h1> <b>Other</b> Friends</h1>

<br>
<%= render 'friends/friends_list' %>

app/views/friends/party.html.erb
<h1>Friends met <b>at a party</b></h1>
<br>
<%= render 'friends/friends_list' %>

app/views/friends/school.html.erb
<h1>Friends met <b>at school</b></h1>

<br>
<%= render 'friends/friends_list' %>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit", edit_friend_path(@friend), class: 'btn btn-success', style: 'border-radius:0px;' %>
  <%= link_to "Back", friends_path, class: 'btn btn-dark', style: 'border-radius:0px;' %>
  <%= link_to "Delete", @friend, class: 'btn btn-danger', style: 'border-radius:0px;', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this item?' } %>
</div>

app/views/friends/work.html.erb
<h1>Friends met <b>at work</b></h1>
<br>
<%= render 'friends/friends_list' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="container">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <p class="navbar-brand"><%= app_title %></p>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= render 'shared/nav_link', label: 'All', path: root_path %>
          <%= render 'shared/nav_link', label: 'Party', path: party_friends_path %>
          <%= render 'shared/nav_link', label: 'Work', path: work_friends_path %>
          <%= render 'shared/nav_link', label: 'School', path: school_friends_path %>
          <%= render 'shared/nav_link', label: 'Holidays', path: holidays_friends_path %>
          <%= render 'shared/nav_link', label: 'Other', path: other_friends_path %>
        </div>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/friends.html.erb
<html>
<head>
  <title>Friends</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>
<body class="container">
<%= yield %>
</body>
</html>

app/views/shared/_nav_link.html.erb
<%= link_to label, path, class: nav_link_class(path) %>